name = "kataly-username-checker"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "SCAN_STATE"
id = "PLACEHOLDER_KV_ID"
